"""added role and rsvp to employee_meetings

Revision ID: 3a1bfdb74224
Revises: 9058e14c5bc6
Create Date: 2024-07-25 16:15:40.194032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1bfdb74224'
down_revision = '9058e14c5bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RSVP', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.drop_column('RSVP')

    # ### end Alembic commands ###
