"""changed employee_meeting to a class

Revision ID: 779fb630a9ef
Revises: 3a1bfdb74224
Create Date: 2024-07-25 17:15:55.937715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779fb630a9ef'
down_revision = '3a1bfdb74224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsvp', sa.Boolean(), nullable=True))
        batch_op.drop_column('RSVP')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RSVP', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('rsvp')

    # ### end Alembic commands ###
