"""changes made

Revision ID: 78670fcd0ef1
Revises: b5c21f57efe6
Create Date: 2024-07-17 15:16:50.553337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78670fcd0ef1'
down_revision = 'b5c21f57efe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_meetings', schema=None) as batch_op:
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('id')
    # ### end Alembic commands ###
