"""changed to department column

Revision ID: 9058e14c5bc6
Revises: 282fe7ff4318
Create Date: 2024-07-24 13:05:16.792473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9058e14c5bc6'
down_revision = '282fe7ff4318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), nullable=False))
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('department')

    # ### end Alembic commands ###
