"""added manager model and relationship between manager and employee

Revision ID: b5c21f57efe6
Revises: efeca5ac1601
Create Date: 2024-07-05 13:33:50.332666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c21f57efe6'
down_revision = 'efeca5ac1601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_employees_manager_id_managers'), 'managers', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employees_manager_id_managers'), type_='foreignkey')
        batch_op.drop_column('manager_id')

    op.drop_table('managers')
    # ### end Alembic commands ###
